### ISSUE TITLE
generates the wrong url

### ISSUE THREAD

**Issue by eikoninaru** [GuDzpoz/flarum-ext-syndication#3]
```
Flarum 0.1.0-beta.15
PHP 7.3.10-1+0~20191008.45+debian9~1.gbp365209
flarum-ext-syndication v0.3.1
```

`/atom/discussions` generates https://www.linuxmint.com.ua/d/463-463-reliz-distributiva-linux-mint-201/1/1 instead https://www.linuxmint.com.ua/d/463-reliz-distributiva-linux-mint-201

**Comment by gudzpoz** [comment]
Probably works now.
It seems flarum has fixed a bug on their end, so the original workaround failed.
Thanks for reporting!

https://github.com/GuDzpoz/flarum-ext-syndication/commit/1bf91a7f7090dad9e9b93b2e0e0ab88805aa002e

**Comment by eikoninaru** [comment]
now everything is fine. ty!

**Comment by eikoninaru** [comment]
now everything is fine. ty!
